
<img src="img/viu_logo.png" width="200">

## 01MIAR - Procesamiento de Datos

![logo](img/python_logo.png)

*Ivan Fuertes / Franklin Alvarez*

In [2]:
import numpy as np
import pandas as pd

# Duarante esta sesión mostraremos números flotantes con una precisión de 2 decimales
pd.set_option('display.precision', 2)

### Uniendo datasets con 'join' y 'merge'
- merge() == join()
 - 'join' utiliza por defecto los índices para unir
- Utilizando el parámetro 'on'
 - Si las columnas difieren, 'left_on' y 'right_on'
 
https://miro.medium.com/v2/resize:fit:1400/1*GigXPhr4Ue2zbrgIIoB8Lw.png

#### Combinar varios datasets 
- En base a un elemento en común (índice)
- MovieLens 'UserId'

In [3]:
import zipfile as zp # para descomprimir archivos zip
import urllib.request # para descargar de URL
import os

# descargar MovieLens dataset
url = 'http://files.grouplens.org/datasets/movielens/ml-1m.zip'  
local_zip = os.path.join("res", "ml-1m.zip")
urllib.request.urlretrieve(url, local_zip)

# descomprimiendo archivo zip
with zp.ZipFile(local_zip, 'r') as zipp: 
    print('Extracting all files...') 
    zipp.extractall(os.path.join("res")) # destino
    print('Done!')

Extracting all files...
Done!

In [4]:
ruta_users = os.path.join("res", "ml-1m", "users.dat")
ruta_ratings = os.path.join("res", "ml-1m", "ratings.dat")
ruta_movies = os.path.join("res", "ml-1m", "movies.dat")

users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
    header=None, names=['UserID','Gender','Age','Occupation','Zip-code'], engine='python', encoding="ISO-8859-1")

ratings_dataset = pd.read_csv(ruta_ratings, sep='::', index_col=0, 
    header=None, names=['UserID','MovieID','Rating','Timestamp'], engine='python', encoding="ISO-8859-1")

movies_dataset = pd.read_csv(ruta_movies, sep='::', index_col=0, 
    header=None, names=['MovieID','Title','Genre'], engine='python', encoding="ISO-8859-1")

In [5]:
display(users_dataset.head(5))
print(len(users_dataset))

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
2           M   56          16    70072
3           M   25          15    55117
4           M   45           7    02460
5           M   25          20    55455

6040

In [6]:
display(ratings_dataset.sample(5))
print(len(ratings_dataset))

        MovieID  Rating  Timestamp
UserID
3547       1994       5  966912386
1680       1104       4  974840851
2938       1136       5  971450849
5289       3075       4  961085240
1181       1416       3  974946529

1000209

In [7]:
display(movies_dataset.sample(5))
print(len(movies_dataset))

                                   Title              Genre
MovieID
1050          Looking for Richard (1996)  Documentary|Drama
1534                  Bonheur, Le (1965)              Drama
848           Spitfire Grill, The (1996)              Drama
2249               My Blue Heaven (1990)             Comedy
968      Night of the Living Dead (1968)      Horror|Sci-Fi

3883

In [8]:
# combinando users y ratings, ¿Cómo?
combined_dataset = users_dataset.merge(ratings_dataset, on='UserID', how='inner') # parametro 'on' define la columna pivote
display(combined_dataset.head(5))
print(len(combined_dataset))

       Gender  Age  Occupation Zip-code  MovieID  Rating  Timestamp
UserID
1           F    1          10    48067     1193       5  978300760
1           F    1          10    48067      661       3  978302109
1           F    1          10    48067      914       3  978301968
1           F    1          10    48067     3408       4  978300275
1           F    1          10    48067     2355       5  978824291

1000209

In [9]:
# combinando movies y el resto
all_dataset = combined_dataset.merge(movies_dataset, on='MovieID', how='outer')
display(all_dataset.sample(5))
print(len(all_dataset))

mask = pd.isnull(all_dataset["Rating"])
all_dataset[mask]["MovieID"].unique()

,Gender,Age,Occupation,Zip-code,MovieID,Rating,Timestamp,Title,Genre
679692,M,25.0,0.0,45245,2502,5.0,9.75e+08,Office Space (1999),Comedy|Romance
468405,M,18.0,4.0,20037,1663,5.0,9.67e+08,Stripes (1981),Comedy
557982,M,25.0,16.0,28542,2033,4.0,9.67e+08,"Black Cauldron, The (1985)",Animation|Children's
979517,F,35.0,11.0,05602,3793,2.0,1.04e+09,X-Men (2000),Action|Sci-Fi
31641,F,25.0,2.0,94040,95,2.0,9.75e+08,Broken Arrow (1996),Action|Thriller

1000386

array([  51,  109,  115,  143,  284,  285,  395,  399,  400,  403,  604,
        620,  625,  629,  636,  654,  675,  676,  683,  693,  699,  713,
        721,  723,  727,  738,  739,  752,  768,  770,  772,  773,  777,
        794,  795,  797,  812,  816,  819,  822,  825,  845,  855,  856,
        857,  871,  873,  890,  894,  979,  983, 1001, 1045, 1052, 1065,
       1075, 1106, 1108, 1109, 1110, 1122, 1137, 1140, 1141, 1143, 1146,
       1155, 1156, 1157, 1158, 1159, 1166, 1308, 1309, 1314, 1318, 1319,
       1368, 1400, 1424, 1443, 1448, 1462, 1467, 1524, 1557, 1559, 1568,
       1577, 1578, 1628, 1697, 1698, 1705, 1706, 1708, 1710, 1716, 1723,
       1738, 1740, 1742, 1757, 1765, 1768, 1774, 1776, 1781, 1789, 1819,
       1847, 2030, 2199, 2216, 2220, 2222, 2224, 2225, 2228, 2229, 2230,
       2270, 2274, 2319, 2489, 2508, 2547, 2564, 2588, 2595, 2601, 2603,
       2604, 2680, 2684, 2698, 2832, 2838, 2910, 2954, 2957, 2958, 2980,
       3009, 3023, 3059, 3080, 3170, 3191, 3193, 3195, 3226, 3227, 3231,
       3234, 3278, 3279, 3332, 3348, 3356, 3369, 3383, 3411, 3455, 3541,
       3558, 3560, 3561, 3582, 3583, 3589, 3630, 3650, 3750, 3829, 3856,
       3907])

#### Concatenate
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html

## Pivot
- Representar los datos en función a varios parámetros, agregando
```python
pivot_table(<lista de valores>, index=<agregador primario>, columns=<agregador secundario>)
```
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html
- https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html

In [10]:
display(all_dataset.pivot_table('Rating', index='Gender', columns='Age'))

# Operación equivalente para cada celda
mask = (all_dataset['Gender'] == 'F') * (all_dataset['Age'] == 1)
F1 = all_dataset[mask].Rating.mean()
print("Valor para F-1:", F1)

Age     1.0   18.0  25.0  35.0  45.0  50.0  56.0
Gender
F       3.62  3.45  3.61  3.66  3.66  3.80  3.92
M       3.52  3.53  3.53  3.60  3.63  3.69  3.72

Valor para F-1: 3.616290925569276

In [11]:
# Podemos agregar funciones o lista de funciones con las que operar
# display(all_dataset.pivot_table('Rating', index='Gender', columns='Age', aggfunc='count'))
display(all_dataset.pivot_table('Rating', index='Gender', columns='Age', aggfunc=['count', 'max', 'mean']))

        count                                               max            \
Age      1.0     18.0    25.0    35.0   45.0   50.0   56.0 1.0  18.0 25.0
Gender
F        8827   45427   91340   49473  24110  18064   9199  5.0  5.0  5.0
M       18384  138109  304216  149530  59523  54426  29581  5.0  5.0  5.0

        ...                 mean
Age     ... 45.0 50.0 56.0  1.0   18.0  25.0  35.0  45.0  50.0  56.0
Gender  ...
F       ...  5.0  5.0  5.0  3.62  3.45  3.61  3.66  3.66  3.80  3.92
M       ...  5.0  5.0  5.0  3.52  3.53  3.53  3.60  3.63  3.69  3.72

[2 rows x 21 columns]

## Agrupaciones
- agg -> funciones estadísticas de agregación
- Series.unique() -> valores únicos
- pd.value_counts -> ocurrencias

In [12]:
valores_unicos = all_dataset[mask].Rating.unique()
print(valores_unicos)

[5. 3. 4. 2. 1.]

In [13]:
ocurrencias = all_dataset[mask]["Rating"].value_counts()
ocurrencias.name = "Número de ocurrencias por cada Rating"
print(ocurrencias)

Rating
4.0    3036
5.0    2301
3.0    2023
2.0     736
1.0     731
Name: Número de ocurrencias por cada Rating, dtype: int64

## Manipulación de strings
```python
split(): separar en bloques en función de un carácter
replace(): reemplazar un carácter por otro
index(): encontrar la posición de un carácter
```

### Ejemplo MovieLens: Separar géneros y año en columnas individuales

In [14]:
# Ejemplo con MovieLens: Genre
## 1: obtener todos los géneros por separado
## 2: crear un dataset de géneros
## 3: por película, marcar género por separado
## 4: Extraer el año de cada peléicula y colocar en columna individual
## 5: Remover el año del título
## 6: unir con dataset genre
display(movies_dataset.head(3))

                           Title                         Genre
MovieID
1               Toy Story (1995)   Animation|Children's|Comedy
2                 Jumanji (1995)  Adventure|Children's|Fantasy
3        Grumpier Old Men (1995)                Comedy|Romance

In [15]:
all_genres = movies_dataset['Genre'].apply(lambda x : x.split('|'))
print(all_genres)

MovieID
1        [Animation, Children's, Comedy]
2       [Adventure, Children's, Fantasy]
3                      [Comedy, Romance]
4                        [Comedy, Drama]
5                               [Comedy]
                      ...
3948                            [Comedy]
3949                             [Drama]
3950                             [Drama]
3951                             [Drama]
3952                   [Drama, Thriller]
Name: Genre, Length: 3883, dtype: object

In [16]:
genres = {genre for x in all_genres for genre in x}
print("Set con todos los géneros:")
print(genres)
print()

# Alternativa usando unique()
genres = pd.unique(pd.Series(all_genres.sum()))
print("Lista con todos los géneros:")
print(genres)

Set con todos los géneros:
{'Fantasy', "Children's", 'Action', 'Mystery', 'Documentary', 'Musical', 'Western', 'Drama', 'Romance', 'War', 'Thriller', 'Sci-Fi', 'Crime', 'Comedy', 'Horror', 'Adventure', 'Film-Noir', 'Animation'}

Lista con todos los géneros:
<StringArray>
[  'Animation',  'Children's',      'Comedy',   'Adventure',     'Fantasy',
     'Romance',       'Drama',      'Action',       'Crime',    'Thriller',
      'Horror',      'Sci-Fi', 'Documentary',         'War',     'Musical',
     'Mystery',   'Film-Noir',     'Western']
Length: 18, dtype: str

In [17]:
# crear tabla con columnas por género
zeros = np.zeros( (len(movies_dataset), len(genres)) )
genres_frame = pd.DataFrame(zeros, columns=genres, index=list(range(1, len(movies_dataset) + 1)))
display(genres_frame.head(3))

,Animation,Children's,Comedy,Adventure,Fantasy,Romance,Drama,Action,Crime,Thriller,Horror,Sci-Fi,Documentary,War,Musical,Mystery,Film-Noir,Western
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
columns_genres = genres_frame.columns # lista de generos (columnas)
print(columns_genres)

# para cada película, marcar género con 1
for i, genre in enumerate(movies_dataset['Genre']):
    inds = columns_genres.get_indexer(genre.split('|')) # retorna los indices correspondientes a los generos de cada pelicula
    genres_frame.iloc[i,inds] = 1 # localiza las columnas del genero correspondiente, marca con 1

display(genres_frame.head(5))

Index(['Animation', 'Children's', 'Comedy', 'Adventure', 'Fantasy', 'Romance',
       'Drama', 'Action', 'Crime', 'Thriller', 'Horror', 'Sci-Fi',
       'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir', 'Western'],
      dtype='str')

,Animation,Children's,Comedy,Adventure,Fantasy,Romance,Drama,Action,Crime,Thriller,Horror,Sci-Fi,Documentary,War,Musical,Mystery,Film-Noir,Western
1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

#### Replace e index para extraer el año de la película

In [19]:
display(movies_dataset.head(2))

                    Title                         Genre
MovieID
1        Toy Story (1995)   Animation|Children's|Comedy
2          Jumanji (1995)  Adventure|Children's|Fantasy

In [20]:
# extraer el año de la columna Title
def split_year(title):
    index = title.index('(')
    return title[index:].replace('(','').replace(')','')
    
# crear nueva columna Year
movies_dataset['Year'] = movies_dataset['Title'].apply(split_year)
display(movies_dataset.head(2))

                    Title                         Genre  Year
MovieID
1        Toy Story (1995)   Animation|Children's|Comedy  1995
2          Jumanji (1995)  Adventure|Children's|Fantasy  1995

In [21]:
# eliminar el año de la columna Title
def remove_year(title):
    index = title.index('(')
    return title[:index-1].rstrip()

movies_dataset['Title'] = movies_dataset['Title'].apply(remove_year)
display(movies_dataset.head(2))

             Title                         Genre  Year
MovieID
1        Toy Story   Animation|Children's|Comedy  1995
2          Jumanji  Adventure|Children's|Fantasy  1995

In [22]:
# unir con dataset original
movies_split_genre = movies_dataset.join(genres_frame)

display(movies_split_genre.head(5))

,Title,Genre,Year,Animation,Children's,Comedy,Adventure,Fantasy,Romance,Drama,...,Crime,Thriller,Horror,Sci-Fi,Documentary,War,Musical,Mystery,Film-Noir,Western
MovieID,,,,,,,,,,,,,,,,,,,,,
1,Toy Story,Animation|Children's|Comedy,1995,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Jumanji,Adventure|Children's|Fantasy,1995,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Grumpier Old Men,Comedy|Romance,1995,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Waiting to Exhale,Comedy|Drama,1995,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Father of the Bride Part II,Comedy,1995,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
# Remover vieja columna de genre
movies_split_genre.drop('Genre', axis=1, inplace=True)
display(movies_split_genre.head(5))

,Title,Year,Animation,Children's,Comedy,Adventure,Fantasy,Romance,Drama,Action,Crime,Thriller,Horror,Sci-Fi,Documentary,War,Musical,Mystery,Film-Noir,Western
MovieID,,,,,,,,,,,,,,,,,,,,
1,Toy Story,1995,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Jumanji,1995,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Grumpier Old Men,1995,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Waiting to Exhale,1995,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Father of the Bride Part II,1995,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

#### Ejemplo con Regular Expressions
Algunos métodos str aceptan expresiones regulares cómo parámetros. Por ejemplo `match()` y `extract()`
- https://docs.python.org/3/library/re.html
- https://regex101.com/
- import re

##### Ejemplo con `match`: Eliminar zip-code con formato erróneo

In [24]:
# ¿Cómo localizar que 'Zip-code' tiene un formato erróneo?
users_dataset.sample(5)

       Gender  Age  Occupation Zip-code
UserID
5864        F   50           1    28043
4195        F   56          13    95050
4820        M   50          11    04210
1761        M   35           0    72058
5391        M   25           7    10016

In [25]:
# Regular expression: ^\d{5}$
# ^ = start of the string
# \d = decimal string
# {5} = 5 repeticiones de decimales
# $ = end of string

mask_correcto = users_dataset['Zip-code'].str.match('^\\d{5}$') # Formato correcto
mask_incorrecto = mask_correcto == False
print("Existen {} entradas con el formato incorrecto".format(mask_incorrecto.sum()))

display(users_dataset[mask_incorrecto])

Existen 81 entradas con el formato incorrecto

       Gender  Age  Occupation    Zip-code
UserID
161         M   45          16  98107-2117
233         F   45          20  37919-4204
293         M   56           1  55337-4056
458         M   50          16  55405-2546
506         M   25          16  55103-1006
...       ...  ...         ...         ...
5682        M   18           0  23455-4959
5904        F   45          12      954025
5925        F   25           0  90035-4444
5967        M   50          16  73069-5429
5985        F   18           4  78705-5221

[81 rows x 4 columns]

In [26]:
index_incorrecto = users_dataset[mask_incorrecto].index
print(index_incorrecto)
users_dataset_clean = users_dataset.drop(index_incorrecto)
print("Tamaño del dataset antes de la limpieza:", users_dataset.shape)
print("Tamaño del dataset después de la limpieza:", users_dataset_clean.shape)

Index([ 161,  233,  293,  458,  506,  541,  567,  868,  913,  939,  946, 1046,
       1081, 1091, 1139, 1201, 1259, 1434, 1463, 1541, 1577, 1595, 1673, 1728,
       1758, 2002, 2087, 2106, 2180, 2210, 2220, 2313, 2585, 2592, 2746, 2853,
       3162, 3287, 3308, 3328, 3333, 3355, 3526, 3738, 3848, 3905, 3938, 3956,
       4012, 4014, 4038, 4124, 4227, 4454, 4458, 4492, 4538, 4723, 4725, 4746,
       4808, 4913, 4965, 4973, 5060, 5100, 5145, 5311, 5337, 5408, 5470, 5473,
       5504, 5510, 5600, 5665, 5682, 5904, 5925, 5967, 5985],
      dtype='int64', name='UserID')
Tamaño del dataset antes de la limpieza: (6040, 4)
Tamaño del dataset después de la limpieza: (5959, 4)

##### Ejemplo con `extract`: Extraer año

In [27]:
movies_dataset = pd.read_csv(ruta_movies, sep='::', index_col=0, 
    header=None, names=['MovieID','Title','Genre'], engine='python', encoding="ISO-8859-1")
display(movies_dataset.head(2))

                    Title                         Genre
MovieID
1        Toy Story (1995)   Animation|Children's|Comedy
2          Jumanji (1995)  Adventure|Children's|Fantasy

In [28]:
# ¿Cómo extraer el año con regex en el formato adecuado?
# Regular expression: (\d{4})
# (= busca apertura parentesis
# \d = decimal string
# {4} = 4 repeticiones de decimales
# ) = cierre de parentesis

movies_year = movies_dataset['Title'].str.extract('(\\d{4})')
movies_dataset['Year'] = movies_year
movies_dataset['Title'] = movies_dataset['Title'].apply(remove_year)

display(movies_dataset.head(2))

             Title                         Genre  Year
MovieID
1        Toy Story   Animation|Children's|Comedy  1995
2          Jumanji  Adventure|Children's|Fantasy  1995

## Ejercicio de operaciones con colecciones: Filtrar películas de 1975
```python
reduce: aplicar una operación y retornar un valor
map: aplicar  una operación y retornar una secuencia
filter: retorna una secuencia con elementos que cumplen una condición
```


#### Reduce
- Aplicar una operación matemática a cada uno de los elementos de una colección
- Diferente de 'apply()' porque retorna un valor numérico
- Ejemplo: Detección de géneros en años específicos

https://docs.python.org/3/library/functools.html

In [61]:
from functools import reduce # necesario para reduce

lista = [1, 3, 5, 7, 9]
print(reduce(lambda x,y: x + y, lista))

25

In [30]:
movies_1975 = movies_split_genre[ movies_split_genre['Year'].str.contains('1975') ]
display(movies_1975.head(4))

,Title,Year,Animation,Children's,Comedy,Adventure,Fantasy,Romance,Drama,Action,Crime,Thriller,Horror,Sci-Fi,Documentary,War,Musical,Mystery,Film-Noir,Western
MovieID,,,,,,,,,,,,,,,,,,,,
716,Switchblade Sisters,1975,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1007,"Apple Dumpling Gang, The",1975,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1009,Escape to Witch Mountain,1975,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1193,One Flew Over the Cuckoo's Nest,1975,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [31]:
any_drama = reduce(lambda x,y : bool(x) | bool(y), movies_1975['Animation']) # hay algún drama en 1975
print(any_drama)

all_comedy = reduce(lambda x,y : bool(x) & bool(y),movies_1975['Comedy']) # son todas las películas de 1975 comedias?
print(all_comedy)

True
False

In [32]:
print(movies_1975['Animation'].any()) # Comprueba si hay algún valor que puede cumplir  
print(movies_1975['Comedy'].all()) # Comprueba si todos los valores son True

True
False

In [33]:
# Observar el tipo de dato antes para ver si es posible aplicar las funciones
print(movies_1975.dtypes)
print()
print("Sólo 2 valores únicos para cualquier género:", movies_1975['Comedy'].unique())

Title              str
Year               str
Animation      float64
Children's     float64
Comedy         float64
Adventure      float64
Fantasy        float64
Romance        float64
Drama          float64
Action         float64
Crime          float64
Thriller       float64
Horror         float64
Sci-Fi         float64
Documentary    float64
War            float64
Musical        float64
Mystery        float64
Film-Noir      float64
Western        float64
dtype: object

Sólo 2 valores únicos para cualquier género: [0. 1.]

#### Map
- Aplicar  una operación (lambda) y retornar una secuencia
- Verifica que géneros aparecen en las películas de 1975
- Elimina las columnas de los géneros que no aparecen

In [34]:
mapa = map(lambda x : (x, movies_1975[x].any()), movies_1975)
print(mapa) # Objeto no realizado con los resultados de la operación lambda

display(pd.Series(mapa)) # Normalmente se realiza con pd.Series

<map object at 0x0000029A8ECCE200>

0            (Title, True)
1             (Year, True)
2        (Animation, True)
3       (Children's, True)
4           (Comedy, True)
5        (Adventure, True)
6          (Fantasy, True)
7          (Romance, True)
8            (Drama, True)
9           (Action, True)
10          (Crime, False)
11        (Thriller, True)
12          (Horror, True)
13          (Sci-Fi, True)
14    (Documentary, False)
15             (War, True)
16        (Musical, False)
17         (Mystery, True)
18       (Film-Noir, True)
19        (Western, False)
dtype: object

In [35]:
mapa = map(lambda x : movies_1975[x].any(), movies_1975)

columnas_validas = movies_1975.columns[pd.Series(mapa)]
movies_1975_clean = movies_1975[columnas_validas]
display(movies_1975_clean.head(4))

,Title,Year,Animation,Children's,Comedy,Adventure,Fantasy,Romance,Drama,Action,Thriller,Horror,Sci-Fi,War,Mystery,Film-Noir
MovieID,,,,,,,,,,,,,,,,
716,Switchblade Sisters,1975,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1007,"Apple Dumpling Gang, The",1975,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1009,Escape to Witch Mountain,1975,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1193,One Flew Over the Cuckoo's Nest,1975,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0

#### Filter
- retorna una secuencia con elementos que cumplen una condición
- Ejemplo: obtener las películas de 1975 que contienen 'The' en el título

In [36]:
filtro = filter(lambda x : 'The' in x, movies_1975_clean['Title'])

for movie in filtro:
    print(movie)
# ¿Están todos los títulos con "The"? si tiene mayúsculas o no...

Apple Dumpling Gang, The
Man Who Would Be King, The
Stepford Wives, The
Rocky Horror Picture Show, The
McCullochs, The
Mirror, The

In [37]:
filtro = filter(lambda x : 'the' in x, movies_1975['Title'].str.lower())
list(filtro)

['apple dumpling gang, the',
 "one flew over the cuckoo's nest",
 'man who would be king, the',
 'stepford wives, the',
 'rocky horror picture show, the',
 'three days of the condor',
 'brother, can you spare a dime?',
 'mccullochs, the',
 'mirror, the']

## Cambiar tipo de datos

In [38]:
movies_1975_bool = pd.DataFrame()
for col in movies_1975_clean:
    if col in genres:
        movies_1975_bool[col] = movies_1975_clean[col].astype(bool)
    else:
        movies_1975_bool[col] = movies_1975_clean[col]

display(movies_1975_bool.head(4))

,Title,Year,Animation,Children's,Comedy,Adventure,Fantasy,Romance,Drama,Action,Thriller,Horror,Sci-Fi,War,Mystery,Film-Noir
MovieID,,,,,,,,,,,,,,,,
716,Switchblade Sisters,1975,False,False,False,False,False,False,True,False,False,True,False,False,False,False
1007,"Apple Dumpling Gang, The",1975,False,True,False,True,True,False,False,False,False,False,True,False,False,False
1009,Escape to Witch Mountain,1975,False,True,True,False,False,False,False,False,False,False,False,False,False,False
1193,One Flew Over the Cuckoo's Nest,1975,False,False,False,True,False,True,False,True,False,False,True,True,False,False

## Transformación de variables (calidad de datos)
- Valores no definidos
- Valores duplicados

In [39]:
matrix = pd.DataFrame(np.random.randint(10,size=(5,10)).astype(float))
matrix[matrix < 2] = np.nan
display(matrix)

     0    1    2    3    4    5    6    7    8    9
0  9.0  9.0  5.0  NaN  6.0  9.0  NaN  NaN  5.0  5.0
1  2.0  3.0  NaN  NaN  4.0  8.0  2.0  7.0  8.0  NaN
2  3.0  7.0  4.0  9.0  NaN  3.0  5.0  2.0  3.0  3.0
3  NaN  8.0  5.0  6.0  9.0  2.0  NaN  4.0  NaN  8.0
4  7.0  4.0  9.0  NaN  NaN  8.0  9.0  NaN  7.0  3.0

In [40]:
# isnull() e isna() son equivalentes

na_col = matrix.isnull().sum()
na_col.name = "Nulos por columna"
print(na_col)
print()

na_row = matrix.isna().sum(axis=1)
na_row.name = "Nulos por fila"
print(na_row)

0    1
1    0
2    1
3    3
4    2
5    0
6    2
7    2
8    1
9    1
Name: Nulos por columna, dtype: int64

0    3
1    3
2    1
3    3
4    3
Name: Nulos por fila, dtype: int64

In [41]:
# Cantidad valores nulos
print(matrix.isnull().sum().sum())

13

In [42]:
# numero de no nulos
na_col = matrix.count()
na_col.name = "Valores válidos por columna"
print(na_col)
print()

na_row = matrix.count(axis=1)
na_row.name = "Valores válidos por fila"
print(na_row)

0    4
1    5
2    4
3    2
4    3
5    5
6    3
7    3
8    4
9    4
Name: Valores válidos por columna, dtype: int64

0    7
1    7
2    9
3    7
4    7
Name: Valores válidos por fila, dtype: int64

In [43]:
# Representación de las filas en las que una determinada columna tiene nulos
display(matrix[matrix[6].isnull()])

     0    1    2    3    4    5   6    7    8    9
0  9.0  9.0  5.0  NaN  6.0  9.0 NaN  NaN  5.0  5.0
3  NaN  8.0  5.0  6.0  9.0  2.0 NaN  4.0  NaN  8.0

In [44]:
# Conteo de valores que aparecen en el dataset
valores = [2, 8]
# Identificación de valores de dominio que se encuentran en un listado
display(matrix[matrix[9].isin(valores)])

    0    1    2    3    4    5   6    7   8    9
3 NaN  8.0  5.0  6.0  9.0  2.0 NaN  4.0 NaN  8.0

In [45]:
display(matrix)

     0    1    2    3    4    5    6    7    8    9
0  9.0  9.0  5.0  NaN  6.0  9.0  NaN  NaN  5.0  5.0
1  2.0  3.0  NaN  NaN  4.0  8.0  2.0  7.0  8.0  NaN
2  3.0  7.0  4.0  9.0  NaN  3.0  5.0  2.0  3.0  3.0
3  NaN  8.0  5.0  6.0  9.0  2.0  NaN  4.0  NaN  8.0
4  7.0  4.0  9.0  NaN  NaN  8.0  9.0  NaN  7.0  3.0

In [46]:
## Tratamiento de valores nulos
print("Eliminar filas con NaN")
display(matrix.dropna(axis=0))

print("Eliminar columnas con NaN")
display(matrix.dropna(axis=1))

Eliminar filas con NaN

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Index: []

Eliminar columnas con NaN

     1    5
0  9.0  9.0
1  3.0  8.0
2  7.0  3.0
3  8.0  2.0
4  4.0  8.0

In [47]:
# eliminar filas donde no hay al menos un número de valores no NaN
display(matrix)
display(matrix.dropna(thresh=8, axis=0))

     0    1    2    3    4    5    6    7    8    9
0  9.0  9.0  5.0  NaN  6.0  9.0  NaN  NaN  5.0  5.0
1  2.0  3.0  NaN  NaN  4.0  8.0  2.0  7.0  8.0  NaN
2  3.0  7.0  4.0  9.0  NaN  3.0  5.0  2.0  3.0  3.0
3  NaN  8.0  5.0  6.0  9.0  2.0  NaN  4.0  NaN  8.0
4  7.0  4.0  9.0  NaN  NaN  8.0  9.0  NaN  7.0  3.0

     0    1    2    3   4    5    6    7    8    9
2  3.0  7.0  4.0  9.0 NaN  3.0  5.0  2.0  3.0  3.0

In [48]:
# sustituir por un valor fijo
display(matrix.fillna(-1))

     0    1    2    3    4    5    6    7    8    9
0  9.0  9.0  5.0 -1.0  6.0  9.0 -1.0 -1.0  5.0  5.0
1  2.0  3.0 -1.0 -1.0  4.0  8.0  2.0  7.0  8.0 -1.0
2  3.0  7.0  4.0  9.0 -1.0  3.0  5.0  2.0  3.0  3.0
3 -1.0  8.0  5.0  6.0  9.0  2.0 -1.0  4.0 -1.0  8.0
4  7.0  4.0  9.0 -1.0 -1.0  8.0  9.0 -1.0  7.0  3.0

In [49]:
# sustituir por valor dinámico (copia)
display(matrix)

display(matrix.bfill())
# display(matrix.ffill())

     0    1    2    3    4    5    6    7    8    9
0  9.0  9.0  5.0  NaN  6.0  9.0  NaN  NaN  5.0  5.0
1  2.0  3.0  NaN  NaN  4.0  8.0  2.0  7.0  8.0  NaN
2  3.0  7.0  4.0  9.0  NaN  3.0  5.0  2.0  3.0  3.0
3  NaN  8.0  5.0  6.0  9.0  2.0  NaN  4.0  NaN  8.0
4  7.0  4.0  9.0  NaN  NaN  8.0  9.0  NaN  7.0  3.0

     0    1    2    3    4    5    6    7    8    9
0  9.0  9.0  5.0  9.0  6.0  9.0  2.0  7.0  5.0  5.0
1  2.0  3.0  4.0  9.0  4.0  8.0  2.0  7.0  8.0  3.0
2  3.0  7.0  4.0  9.0  9.0  3.0  5.0  2.0  3.0  3.0
3  7.0  8.0  5.0  6.0  9.0  2.0  9.0  4.0  7.0  8.0
4  7.0  4.0  9.0  NaN  NaN  8.0  9.0  NaN  7.0  3.0

In [50]:
# sustituir por valor dinámico (interpolación)
display(matrix)
display(matrix.interpolate())

     0    1    2    3    4    5    6    7    8    9
0  9.0  9.0  5.0  NaN  6.0  9.0  NaN  NaN  5.0  5.0
1  2.0  3.0  NaN  NaN  4.0  8.0  2.0  7.0  8.0  NaN
2  3.0  7.0  4.0  9.0  NaN  3.0  5.0  2.0  3.0  3.0
3  NaN  8.0  5.0  6.0  9.0  2.0  NaN  4.0  NaN  8.0
4  7.0  4.0  9.0  NaN  NaN  8.0  9.0  NaN  7.0  3.0

     0    1    2    3    4    5    6    7    8    9
0  9.0  9.0  5.0  NaN  6.0  9.0  NaN  NaN  5.0  5.0
1  2.0  3.0  4.5  NaN  4.0  8.0  2.0  7.0  8.0  4.0
2  3.0  7.0  4.0  9.0  6.5  3.0  5.0  2.0  3.0  3.0
3  5.0  8.0  5.0  6.0  9.0  2.0  7.0  4.0  5.0  8.0
4  7.0  4.0  9.0  6.0  9.0  8.0  9.0  4.0  7.0  3.0

#### Tratar valores duplicados

In [51]:
serie = pd.Series(['a','b','c','a','c','a','g'])
print(serie.duplicated())

0    False
1    False
2    False
3     True
4     True
5     True
6    False
dtype: bool

In [52]:
df = all_dataset.copy()
display(df.head(3))

# Eliminación de los duplicados en una columna definida
df2 = df.drop_duplicates(subset="Title", keep='last', inplace=False)
df2.info()

,Gender,Age,Occupation,Zip-code,MovieID,Rating,Timestamp,Title,Genre
0,F,1.0,10.0,48067,1,5.0,9.79e+08,Toy Story (1995),Animation|Children's|Comedy
1,F,50.0,9.0,55117,1,4.0,9.78e+08,Toy Story (1995),Animation|Children's|Comedy
2,M,25.0,12.0,11413,1,4.0,9.78e+08,Toy Story (1995),Animation|Children's|Comedy

<class 'pandas.DataFrame'>
Index: 3883 entries, 2076 to 1000385
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      3706 non-null   str
 1   Age         3706 non-null   float64
 2   Occupation  3706 non-null   float64
 3   Zip-code    3706 non-null   str
 4   MovieID     3883 non-null   int64
 5   Rating      3706 non-null   float64
 6   Timestamp   3706 non-null   float64
 7   Title       3883 non-null   str
 8   Genre       3883 non-null   str
dtypes: float64(4), int64(1), str(4)
memory usage: 303.4 KB

## Valores categóricos

In [53]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1000386 entries, 0 to 1000385
Data columns (total 9 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   Gender      1000209 non-null  str
 1   Age         1000209 non-null  float64
 2   Occupation  1000209 non-null  float64
 3   Zip-code    1000209 non-null  str
 4   MovieID     1000386 non-null  int64
 5   Rating      1000209 non-null  float64
 6   Timestamp   1000209 non-null  float64
 7   Title       1000386 non-null  str
 8   Genre       1000386 non-null  str
dtypes: float64(4), int64(1), str(4)
memory usage: 68.7 MB
None

In [54]:
df["Age"] = pd.Categorical(df["Age"])

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000386 entries, 0 to 1000385
Data columns (total 9 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   Gender      1000209 non-null  str
 1   Age         1000209 non-null  category
 2   Occupation  1000209 non-null  float64
 3   Zip-code    1000209 non-null  str
 4   MovieID     1000386 non-null  int64
 5   Rating      1000209 non-null  float64
 6   Timestamp   1000209 non-null  float64
 7   Title       1000386 non-null  str
 8   Genre       1000386 non-null  str
dtypes: category(1), float64(3), int64(1), str(4)
memory usage: 62.0 MB

In [55]:
df["Rating"] = df["Rating"].astype("category")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000386 entries, 0 to 1000385
Data columns (total 9 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   Gender      1000209 non-null  str
 1   Age         1000209 non-null  category
 2   Occupation  1000209 non-null  float64
 3   Zip-code    1000209 non-null  str
 4   MovieID     1000386 non-null  int64
 5   Rating      1000209 non-null  category
 6   Timestamp   1000209 non-null  float64
 7   Title       1000386 non-null  str
 8   Genre       1000386 non-null  str
dtypes: category(2), float64(2), int64(1), str(4)
memory usage: 55.3 MB

#### Discretización (valores categóricos)
- Tras Series y DataFrame, objeto para categorías: Categorical
```python
categorias = pd.cut(<valores>, <bins>) 
```

In [56]:
# especificar los bloques
bins = [0,18,35,65,99, np.inf] # Límites para definir 5 categorías
etiquetas = ["Menor","Joven","Adulto","Mayor","Anciano"]
edades = [16,25,18,71,44,100,12]

categorias = pd.cut(edades,bins,labels=etiquetas)
display(categorias)
print()
print("Verificar si pertenece a una categoría:")
display(categorias == "Menor")

['Menor', 'Joven', 'Menor', 'Mayor', 'Adulto', 'Anciano', 'Menor']
Categories (5, str): ['Menor' < 'Joven' < 'Adulto' < 'Mayor' < 'Anciano']

Verificar si pertenece a una categoría:

array([ True, False,  True, False, False, False,  True])

In [57]:
# Cuantos por categoría?
categorias.value_counts()

Menor      3
Joven      1
Adulto     1
Mayor      1
Anciano    1
Name: count, dtype: int64

In [58]:
# Categorías por rango de valores
bins = 3
etiquetas = ["Eliminado", "Repechaje", "Clasificado"]
puntos = [0,6,8,16,25,18,71,44,100]

# Utilizar cut me devuelve rangos del mismo tamaño (max - min)/bin
categorias = pd.cut(puntos, bins, labels=etiquetas) 
print(categorias)
print()
print(categorias.value_counts())

['Eliminado', 'Eliminado', 'Eliminado', 'Eliminado', 'Eliminado', 'Eliminado', 'Clasificado', 'Repechaje', 'Clasificado']
Categories (3, str): ['Eliminado' < 'Repechaje' < 'Clasificado']

Eliminado      6
Repechaje      1
Clasificado    2
Name: count, dtype: int64

In [59]:
bins = 3
etiquetas = ["Eliminado", "Repechaje", "Clasificado"]
edades = [1,6,8,16,25,18,71,44,100]

# Utilizar qcut me devuelve distribuciones del mismo tamaño
categorias = pd.qcut(edades,bins,labels=etiquetas) # rangos homogéneos (similar número de valores)
print(categorias)
print()
print(categorias.value_counts())

['Eliminado', 'Eliminado', 'Eliminado', 'Repechaje', 'Repechaje', 'Repechaje', 'Clasificado', 'Clasificado', 'Clasificado']
Categories (3, str): ['Eliminado' < 'Repechaje' < 'Clasificado']

Eliminado      3
Repechaje      3
Clasificado    3
Name: count, dtype: int64